"""add notification fields to salesperson

Revision ID: 07ccd7f12f44
Revises: ca38600e3696
Create Date: 2026-02-11 15:19:31.561190
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '07ccd7f12f44'
down_revision: Union[str, None] = 'ca38600e3696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salespeople', sa.Column('notification_webhook_url', sa.String(length=500), nullable=True))
    op.add_column('salespeople', sa.Column('notify_on_new_lead', sa.Boolean(), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE salespeople SET notify_on_new_lead = true WHERE notify_on_new_lead IS NULL")
    # Now make it NOT NULL
    op.alter_column('salespeople', 'notify_on_new_lead', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salespeople', 'notify_on_new_lead')
    op.drop_column('salespeople', 'notification_webhook_url')
    # ### end Alembic commands ###
