"""add_user_id_to_salesperson_and_salesperson_role

Revision ID: 092adbaa71df
Revises: 74459fdeca34
Create Date: 2026-02-11 15:48:47.466963
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '092adbaa71df'
down_revision: Union[str, None] = '74459fdeca34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salespeople', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'salespeople', ['user_id'])
    op.create_foreign_key(None, 'salespeople', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'salespeople', type_='foreignkey')
    op.drop_constraint(None, 'salespeople', type_='unique')
    op.drop_column('salespeople', 'user_id')
    # ### end Alembic commands ###
