"""Add exam registration fields

Revision ID: 3110d53c1eee
Revises: c53f02874a2f
Create Date: 2026-03-30 15:26:32.440811
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = '3110d53c1eee'
down_revision: Union[str, None] = 'c53f02874a2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('material', sa.Text(), nullable=True))
    op.add_column('exams', sa.Column('registration_price', sa.Integer(), nullable=True))
    op.add_column('exams', sa.Column('registration_url', sa.String(length=500), nullable=True))
    # Add with default to avoid NOT NULL violation on existing rows
    op.add_column(
        'exams',
        sa.Column('is_registration_open', sa.Boolean(), server_default=sa.text('true'), nullable=False)
    )
    # Drop server default (keep column NOT NULL)
    op.alter_column('exams', 'is_registration_open', server_default=None)
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exams', 'is_registration_open')
    op.drop_column('exams', 'registration_url')
    op.drop_column('exams', 'registration_price')
    op.drop_column('exams', 'material')
    # ### end Alembic commands ###

