"""sync_remaining_schema_diffs

Revision ID: 611befc42c3c
Revises: 6d51a6714aac
Create Date: 2026-02-10 23:00:15.260814
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '611befc42c3c'
down_revision: Union[str, None] = '6d51a6714aac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_collections_commitment', 'collections', ['commitment_id'], unique=False)
    op.create_index('idx_collections_nedarim', 'collections', ['nedarim_donation_id'], unique=False)
    op.create_index('idx_commitments_nedarim', 'commitments', ['nedarim_subscription_id'], unique=False)
    op.alter_column('expenses', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               nullable=False)
    op.alter_column('expenses', 'expense_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('expenses', 'vendor',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.drop_index('idx_leads_course', table_name='leads')
    op.drop_constraint('leads_course_id_fkey', 'leads', type_='foreignkey')
    op.create_foreign_key(None, 'leads', 'courses', ['course_id'], ['id'])
    op.create_index('idx_payments_nedarim', 'payments', ['nedarim_donation_id'], unique=False)
    op.drop_column('students', 'nedarim_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('nedarim_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index('idx_payments_nedarim', table_name='payments')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.create_foreign_key('leads_course_id_fkey', 'leads', 'courses', ['course_id'], ['id'], ondelete='SET NULL')
    op.create_index('idx_leads_course', 'leads', ['course_id'], unique=False)
    op.alter_column('expenses', 'vendor',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.alter_column('expenses', 'expense_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('expenses', 'description',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_index('idx_commitments_nedarim', table_name='commitments')
    op.drop_index('idx_collections_nedarim', table_name='collections')
    op.drop_index('idx_collections_commitment', table_name='collections')
    # ### end Alembic commands ###
