"""add_test_logs_table

Revision ID: 6c3f271d853b
Revises: 840f7bd52ad2
Create Date: 2026-04-21 16:55:22.755999
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers
revision: str = '6c3f271d853b'
down_revision: Union[str, None] = '840f7bd52ad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_type', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_test_logs_type', 'test_logs', ['test_type'], unique=False)
    op.create_index('idx_test_logs_user', 'test_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_test_logs_user', table_name='test_logs')
    op.drop_index('idx_test_logs_type', table_name='test_logs')
    op.drop_table('test_logs')
    # ### end Alembic commands ###
