"""add chat tables

Revision ID: 6fa1e9fa08c6
Revises: 990d4ef348a4
Create Date: 2026-02-18 18:52:11.463231
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '6fa1e9fa08c6'
down_revision: Union[str, None] = '990d4ef348a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('is_sales_team', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_threads_sales_team', 'chat_threads', ['is_sales_team'], unique=False)
    op.create_index('idx_chat_threads_type', 'chat_threads', ['thread_type'], unique=False)
    op.create_index('idx_chat_threads_updated', 'chat_threads', ['updated_at'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('sender_user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('reply_to_message_id', sa.Integer(), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('pinned_by_user_id', sa.Integer(), nullable=True),
    sa.Column('pinned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pinned_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reply_to_message_id'], ['chat_messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_msg_created', 'chat_messages', ['created_at'], unique=False)
    op.create_index('idx_chat_msg_pinned', 'chat_messages', ['is_pinned'], unique=False)
    op.create_index('idx_chat_msg_reply', 'chat_messages', ['reply_to_message_id'], unique=False)
    op.create_index('idx_chat_msg_sender', 'chat_messages', ['sender_user_id'], unique=False)
    op.create_index('idx_chat_msg_thread', 'chat_messages', ['thread_id'], unique=False)
    op.create_table('chat_thread_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id', 'user_id', name='uq_chat_thread_member')
    )
    op.create_index('idx_chat_members_thread', 'chat_thread_members', ['thread_id'], unique=False)
    op.create_index('idx_chat_members_user', 'chat_thread_members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_chat_members_user', table_name='chat_thread_members')
    op.drop_index('idx_chat_members_thread', table_name='chat_thread_members')
    op.drop_table('chat_thread_members')
    op.drop_index('idx_chat_msg_thread', table_name='chat_messages')
    op.drop_index('idx_chat_msg_sender', table_name='chat_messages')
    op.drop_index('idx_chat_msg_reply', table_name='chat_messages')
    op.drop_index('idx_chat_msg_pinned', table_name='chat_messages')
    op.drop_index('idx_chat_msg_created', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('idx_chat_threads_updated', table_name='chat_threads')
    op.drop_index('idx_chat_threads_type', table_name='chat_threads')
    op.drop_index('idx_chat_threads_sales_team', table_name='chat_threads')
    op.drop_table('chat_threads')
    # ### end Alembic commands ###
