"""add_webhook_logs_and_salesperson_notifications

Revision ID: 74459fdeca34
Revises: 07ccd7f12f44
Create Date: 2026-02-11 15:26:55.049946
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '74459fdeca34'
down_revision: Union[str, None] = '07ccd7f12f44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
