"""Add last_edited_at to leads

Revision ID: 803ce066fbdf
Revises: df86256cca0b
Create Date: 2026-02-12 01:49:06.031122
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '803ce066fbdf'
down_revision: Union[str, None] = 'df86256cca0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('last_edited_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'last_edited_at')
    # ### end Alembic commands ###
