"""add_lead_tracking_and_payment_fields

Revision ID: 912d528af40f
Revises: 611befc42c3c
Create Date: 2026-02-10 23:32:20.788512
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '912d528af40f'
down_revision: Union[str, None] = '611befc42c3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_assignment_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salesperson_id', sa.Integer(), nullable=False),
    sa.Column('daily_lead_limit', sa.Integer(), nullable=True),
    sa.Column('daily_leads_assigned', sa.Integer(), nullable=False),
    sa.Column('last_reset_date', sa.Date(), nullable=True),
    sa.Column('priority_weight', sa.Integer(), nullable=False),
    sa.Column('max_open_leads', sa.Integer(), nullable=True),
    sa.Column('status_filters', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['salesperson_id'], ['salespeople.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('salesperson_id')
    )
    op.create_index('idx_assignment_rules_active', 'sales_assignment_rules', ['is_active'], unique=False)
    op.create_index('idx_assignment_rules_salesperson', 'sales_assignment_rules', ['salesperson_id'], unique=False)
    op.add_column('leads', sa.Column('lead_response', sa.String(length=100), nullable=True))
    op.add_column('leads', sa.Column('follow_up_count', sa.Integer(), nullable=False))
    op.add_column('leads', sa.Column('last_contact_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('leads', sa.Column('discount_notes', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('approval_method', sa.String(length=50), nullable=True))
    op.add_column('leads', sa.Column('approval_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'approval_date')
    op.drop_column('leads', 'approval_method')
    op.drop_column('leads', 'discount_notes')
    op.drop_column('leads', 'last_contact_date')
    op.drop_column('leads', 'follow_up_count')
    op.drop_column('leads', 'lead_response')
    op.drop_index('idx_assignment_rules_salesperson', table_name='sales_assignment_rules')
    op.drop_index('idx_assignment_rules_active', table_name='sales_assignment_rules')
    op.drop_table('sales_assignment_rules')
    # ### end Alembic commands ###
