"""add inbound_emails table for webhook email sync

Revision ID: 990d4ef348a4
Revises: d29c37a74bf5
Create Date: 2026-02-15 12:30:05.819989
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '990d4ef348a4'
down_revision: Union[str, None] = 'd29c37a74bf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
