"""add course tracks and sessions system

Revision ID: ac56d9a0432b
Revises: 8877c651d63f
Create Date: 2026-02-10 23:58:18.506759
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'ac56d9a0432b'
down_revision: Union[str, None] = '8877c651d63f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create course_tracks table
    op.create_table('course_tracks',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('course_id', sa.Integer(), nullable=False),
        sa.Column('lecturer_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=300), nullable=False),
        sa.Column('day_of_week', sa.String(length=20), nullable=False),
        sa.Column('start_time', sa.String(length=10), nullable=False),
        sa.Column('city', sa.String(length=200), nullable=False),
        sa.Column('zoom_url', sa.String(length=500), nullable=True),
        sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('current_module_id', sa.Integer(), nullable=True),
        sa.Column('current_session_number', sa.Integer(), nullable=False, server_default='1'),
        sa.Column('last_session_date', sa.Date(), nullable=True),
        sa.Column('next_entry_date', sa.Date(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['current_module_id'], ['course_modules.id']),
        sa.ForeignKeyConstraint(['lecturer_id'], ['lecturers.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tracks_active', 'course_tracks', ['is_active'], unique=False)
    op.create_index('idx_tracks_city', 'course_tracks', ['city'], unique=False)
    op.create_index('idx_tracks_course', 'course_tracks', ['course_id'], unique=False)
    op.create_index('idx_tracks_lecturer', 'course_tracks', ['lecturer_id'], unique=False)
    
    # Create course_sessions table
    op.create_table('course_sessions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('track_id', sa.Integer(), nullable=False),
        sa.Column('module_id', sa.Integer(), nullable=False),
        sa.Column('session_number', sa.Integer(), nullable=False),
        sa.Column('session_date', sa.Date(), nullable=False),
        sa.Column('actual_start_time', sa.String(length=10), nullable=True),
        sa.Column('actual_end_time', sa.String(length=10), nullable=True),
        sa.Column('recording_url', sa.String(length=500), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=False, server_default='מתוכנן'),
        sa.Column('is_entry_point', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['module_id'], ['course_modules.id']),
        sa.ForeignKeyConstraint(['track_id'], ['course_tracks.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sessions_date', 'course_sessions', ['session_date'], unique=False)
    op.create_index('idx_sessions_entry_point', 'course_sessions', ['is_entry_point'], unique=False)
    op.create_index('idx_sessions_module', 'course_sessions', ['module_id'], unique=False)
    op.create_index('idx_sessions_track', 'course_sessions', ['track_id'], unique=False)
    
    # Add columns to existing tables
    op.add_column('attendance', sa.Column('session_id', sa.Integer(), nullable=True))
    op.create_index('idx_attendance_session', 'attendance', ['session_id'], unique=False)
    op.create_foreign_key(None, 'attendance', 'course_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.add_column('enrollments', sa.Column('track_id', sa.Integer(), nullable=True))
    op.add_column('enrollments', sa.Column('entry_session_id', sa.Integer(), nullable=True))
    op.create_index('idx_enrollments_track', 'enrollments', ['track_id'], unique=False)
    op.create_foreign_key(None, 'enrollments', 'course_sessions', ['entry_session_id'], ['id'])
    op.create_foreign_key(None, 'enrollments', 'course_tracks', ['track_id'], ['id'])
    op.add_column('lead_products', sa.Column('track_id', sa.Integer(), nullable=True))
    op.add_column('lead_products', sa.Column('entry_session_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lead_products', 'course_sessions', ['entry_session_id'], ['id'])
    op.create_foreign_key(None, 'lead_products', 'course_tracks', ['track_id'], ['id'])
    op.add_column('leads', sa.Column('interested_track_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'leads', 'course_tracks', ['interested_track_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_column('leads', 'interested_track_id')
    op.drop_constraint(None, 'lead_products', type_='foreignkey')
    op.drop_constraint(None, 'lead_products', type_='foreignkey')
    op.drop_column('lead_products', 'entry_session_id')
    op.drop_column('lead_products', 'track_id')
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.drop_index('idx_enrollments_track', table_name='enrollments')
    op.drop_column('enrollments', 'entry_session_id')
    op.drop_column('enrollments', 'track_id')
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.drop_index('idx_attendance_session', table_name='attendance')
    op.drop_column('attendance', 'session_id')
    
    # Drop course_sessions table
    op.drop_index('idx_sessions_track', table_name='course_sessions')
    op.drop_index('idx_sessions_module', table_name='course_sessions')
    op.drop_index('idx_sessions_entry_point', table_name='course_sessions')
    op.drop_index('idx_sessions_date', table_name='course_sessions')
    op.drop_table('course_sessions')
    
    # Drop course_tracks table
    op.drop_index('idx_tracks_lecturer', table_name='course_tracks')
    op.drop_index('idx_tracks_course', table_name='course_tracks')
    op.drop_index('idx_tracks_city', table_name='course_tracks')
    op.drop_index('idx_tracks_active', table_name='course_tracks')
    op.drop_table('course_tracks')
    # ### end Alembic commands ###
