"""add chat message read receipts

Revision ID: add_chat_message_read_receipts
Revises: 6fa1e9fa08c6
Create Date: 2026-04-22 14:30:00.000000
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'add_chat_message_read_receipts'
down_revision: Union[str, None] = '6fa1e9fa08c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_message_read_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', name='uq_chat_msg_read_receipt')
    )
    op.create_index('idx_chat_read_msg', 'chat_message_read_receipts', ['message_id'], unique=False)
    op.create_index('idx_chat_read_user', 'chat_message_read_receipts', ['user_id'], unique=False)
    op.create_index('idx_chat_read_at', 'chat_message_read_receipts', ['read_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_chat_read_at', table_name='chat_message_read_receipts')
    op.drop_index('idx_chat_read_user', table_name='chat_message_read_receipts')
    op.drop_index('idx_chat_read_msg', table_name='chat_message_read_receipts')
    op.drop_table('chat_message_read_receipts')
    # ### end Alembic commands ###
