"""add send_reminder to sales_tasks

Revision ID: add_send_reminder_to_sales_tasks
Revises: add_chat_message_read_receipts
Create Date: 2026-04-22 14:35:00.000000
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'add_send_reminder_to_sales_tasks'
down_revision: Union[str, None] = '6fa1e9fa08c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_tasks', sa.Column('send_reminder', sa.Boolean(), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE sales_tasks SET send_reminder = true WHERE send_reminder IS NULL")
    # Now make it NOT NULL with default
    op.alter_column('sales_tasks', 'send_reminder', nullable=False, server_default=sa.true())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_tasks', 'send_reminder')
    # ### end Alembic commands ###
