"""Add sales assignment rules table

Revision ID: b421f49e3414
Revises: c7df05879e23
Create Date: 2026-02-11 00:31:50.814213
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'b421f49e3414'
down_revision: Union[str, None] = 'c7df05879e23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
