"""Add exam dates and registrations

Revision ID: b67e5a7290e1
Revises: 925a8ee3a9f0
Create Date: 2026-03-30 14:16:05.125724
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'b67e5a7290e1'
down_revision: Union[str, None] = '925a8ee3a9f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create exam_dates table
    op.create_table('exam_dates',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('description', sa.String(length=500), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('max_registrations', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_dates_date'), 'exam_dates', ['date'], unique=False)
    op.create_index(op.f('ix_exam_dates_is_active'), 'exam_dates', ['is_active'], unique=False)
    
    # Create exam_date_exams table (many-to-many)
    op.create_table('exam_date_exams',
        sa.Column('exam_date_id', sa.Integer(), nullable=False),
        sa.Column('exam_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['exam_date_id'], ['exam_dates.id'], ),
        sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
        sa.PrimaryKeyConstraint('exam_date_id', 'exam_id')
    )
    
    # Create exam_registrations table
    op.create_table('exam_registrations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('exam_date_id', sa.Integer(), nullable=False),
        sa.Column('exam_id', sa.Integer(), nullable=False),
        sa.Column('examinee_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('registration_code', sa.String(length=20), nullable=False),
        sa.Column('notes', sa.String(length=500), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['exam_date_id'], ['exam_dates.id'], ),
        sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
        sa.ForeignKeyConstraint(['examinee_id'], ['examinees.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('registration_code')
    )
    op.create_index(op.f('ix_exam_registrations_exam_date_id'), 'exam_registrations', ['exam_date_id'], unique=False)
    op.create_index(op.f('ix_exam_registrations_exam_id'), 'exam_registrations', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_registrations_examinee_id'), 'exam_registrations', ['examinee_id'], unique=False)
    op.create_index(op.f('ix_exam_registrations_status'), 'exam_registrations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exam_registrations_status'), table_name='exam_registrations')
    op.drop_index(op.f('ix_exam_registrations_examinee_id'), table_name='exam_registrations')
    op.drop_index(op.f('ix_exam_registrations_exam_id'), table_name='exam_registrations')
    op.drop_index(op.f('ix_exam_registrations_exam_date_id'), table_name='exam_registrations')
    op.drop_table('exam_registrations')
    op.drop_table('exam_date_exams')
    op.drop_index(op.f('ix_exam_dates_is_active'), table_name='exam_dates')
    op.drop_index(op.f('ix_exam_dates_date'), table_name='exam_dates')
    op.drop_table('exam_dates')
    # ### end Alembic commands ###
