"""Remove Product table, add pricing to Course, update Lead to use selected_course_id

Revision ID: c7df05879e23
Revises: ac56d9a0432b
Create Date: 2026-02-11 00:00:52.572201
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = 'c7df05879e23'
down_revision: Union[str, None] = 'ac56d9a0432b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First, drop foreign keys and columns that reference products table
    op.drop_constraint('enrollments_product_id_fkey', 'enrollments', type_='foreignkey')
    op.drop_column('enrollments', 'product_id')
    
    op.drop_constraint('lead_products_product_id_fkey', 'lead_products', type_='foreignkey')
    op.drop_column('lead_products', 'product_id')
    
    op.drop_constraint('leads_selected_product_id_fkey', 'leads', type_='foreignkey')
    op.drop_column('leads', 'selected_product_id')
    
    # Now safe to drop products table
    op.drop_table('products')
    
    # Add new columns and constraints
    op.add_column('attendance', sa.Column('session_id', sa.Integer(), nullable=True))
    op.create_index('idx_attendance_session', 'attendance', ['session_id'], unique=False)
    op.create_foreign_key(None, 'attendance', 'course_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    
    op.add_column('courses', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('courses', sa.Column('payments_count', sa.Integer(), nullable=False, server_default='1'))
    
    op.add_column('enrollments', sa.Column('track_id', sa.Integer(), nullable=True))
    op.add_column('enrollments', sa.Column('entry_session_id', sa.Integer(), nullable=True))
    op.create_index('idx_enrollments_track', 'enrollments', ['track_id'], unique=False)
    op.create_foreign_key(None, 'enrollments', 'course_sessions', ['entry_session_id'], ['id'])
    op.create_foreign_key(None, 'enrollments', 'course_tracks', ['track_id'], ['id'])
    
    op.add_column('lead_products', sa.Column('course_id', sa.Integer(), nullable=True))
    op.add_column('lead_products', sa.Column('track_id', sa.Integer(), nullable=True))
    op.add_column('lead_products', sa.Column('entry_session_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lead_products', 'course_sessions', ['entry_session_id'], ['id'])
    op.create_foreign_key(None, 'lead_products', 'course_tracks', ['track_id'], ['id'])
    op.create_foreign_key(None, 'lead_products', 'courses', ['course_id'], ['id'])
    
    op.add_column('leads', sa.Column('interested_track_id', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('selected_course_id', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('selected_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('leads', sa.Column('selected_payments_count', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('selected_payment_day', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'leads', 'courses', ['selected_course_id'], ['id'])
    op.create_foreign_key(None, 'leads', 'course_tracks', ['interested_track_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('selected_product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.create_foreign_key('leads_selected_product_id_fkey', 'leads', 'lead_products', ['selected_product_id'], ['id'])
    op.drop_column('leads', 'selected_payment_day')
    op.drop_column('leads', 'selected_payments_count')
    op.drop_column('leads', 'selected_price')
    op.drop_column('leads', 'selected_course_id')
    op.drop_column('leads', 'interested_track_id')
    op.add_column('lead_products', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'lead_products', type_='foreignkey')
    op.drop_constraint(None, 'lead_products', type_='foreignkey')
    op.drop_constraint(None, 'lead_products', type_='foreignkey')
    op.create_foreign_key('lead_products_product_id_fkey', 'lead_products', 'products', ['product_id'], ['id'])
    op.drop_column('lead_products', 'entry_session_id')
    op.drop_column('lead_products', 'track_id')
    op.drop_column('lead_products', 'course_id')
    op.add_column('enrollments', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.create_foreign_key('enrollments_product_id_fkey', 'enrollments', 'products', ['product_id'], ['id'])
    op.drop_index('idx_enrollments_track', table_name='enrollments')
    op.drop_column('enrollments', 'entry_session_id')
    op.drop_column('enrollments', 'track_id')
    op.drop_column('courses', 'payments_count')
    op.drop_column('courses', 'price')
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.drop_index('idx_attendance_session', table_name='attendance')
    op.drop_column('attendance', 'session_id')
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('product_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('product_number_en', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('payments_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='products_pkey')
    )
    # ### end Alembic commands ###
