"""add file_data column for db storage

Revision ID: ca38600e3696
Revises: d53ed2cb9db5
Create Date: 2026-02-11 14:55:40.838590
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'ca38600e3696'
down_revision: Union[str, None] = 'd53ed2cb9db5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('webhook_type', sa.String(length=50), nullable=False),
    sa.Column('source_ip', sa.String(length=100), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('parsed_data', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('result_data', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_webhook_logs_created', 'webhook_logs', ['created_at'], unique=False)
    op.create_index('idx_webhook_logs_entity', 'webhook_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_webhook_logs_type', 'webhook_logs', ['webhook_type'], unique=False)
    op.add_column('files', sa.Column('file_data', sa.LargeBinary(), nullable=True))
    op.alter_column('files', 'storage_key',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'storage_key',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_column('files', 'file_data')
    op.drop_index('idx_webhook_logs_type', table_name='webhook_logs')
    op.drop_index('idx_webhook_logs_entity', table_name='webhook_logs')
    op.drop_index('idx_webhook_logs_created', table_name='webhook_logs')
    op.drop_table('webhook_logs')
    # ### end Alembic commands ###
