"""add last_edited_at to leads

Revision ID: d29c37a74bf5
Revises: 803ce066fbdf
Create Date: 2026-02-12 22:17:22.988200
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'd29c37a74bf5'
down_revision: Union[str, None] = '803ce066fbdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
