"""add_lead_conversion_tracking_and_class_manager_tasks

Revision ID: d53ed2cb9db5
Revises: e3a9ae9a693e
Create Date: 2026-02-11 02:12:40.646929
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'd53ed2cb9db5'
down_revision: Union[str, None] = 'e3a9ae9a693e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('payment_completed', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('leads', sa.Column('payment_completed_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('leads', sa.Column('payment_completed_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('leads', sa.Column('payment_completed_method', sa.String(length=50), nullable=True))
    op.add_column('leads', sa.Column('payment_reference', sa.String(length=200), nullable=True))
    op.add_column('leads', sa.Column('payment_verified', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('leads', sa.Column('kinyan_signed', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('leads', sa.Column('kinyan_signed_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('leads', sa.Column('kinyan_method', sa.String(length=50), nullable=True))
    op.add_column('leads', sa.Column('kinyan_file_url', sa.String(length=500), nullable=True))
    op.add_column('leads', sa.Column('kinyan_notes', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('shipping_details_complete', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('leads', sa.Column('shipping_full_address', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('shipping_city', sa.String(length=200), nullable=True))
    op.add_column('leads', sa.Column('shipping_postal_code', sa.String(length=20), nullable=True))
    op.add_column('leads', sa.Column('shipping_phone', sa.String(length=50), nullable=True))
    op.add_column('leads', sa.Column('shipping_notes', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('student_chat_added', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('leads', sa.Column('student_chat_link', sa.String(length=500), nullable=True))
    op.add_column('leads', sa.Column('student_chat_platform', sa.String(length=50), nullable=True))
    op.add_column('leads', sa.Column('student_chat_added_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('leads', sa.Column('handoff_to_manager', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('leads', sa.Column('handoff_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('leads', sa.Column('handoff_manager_id', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('handoff_completed', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('leads', sa.Column('handoff_completed_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('leads', sa.Column('conversion_checklist_complete', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('leads', sa.Column('conversion_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('leads', sa.Column('conversion_completed_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'leads', 'users', ['handoff_manager_id'], ['id'])
    op.create_foreign_key(None, 'leads', 'users', ['conversion_completed_by_id'], ['id'])
    op.add_column('sales_tasks', sa.Column('task_type', sa.String(length=50), nullable=False, server_default='sales'))
    op.add_column('sales_tasks', sa.Column('assigned_to_user_id', sa.Integer(), nullable=True))
    op.add_column('sales_tasks', sa.Column('auto_created', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('sales_tasks', sa.Column('parent_lead_conversion', sa.Boolean(), nullable=False, server_default='false'))
    op.alter_column('sales_tasks', 'salesperson_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('idx_tasks_assigned_user', 'sales_tasks', ['assigned_to_user_id'], unique=False)
    op.create_index('idx_tasks_type', 'sales_tasks', ['task_type'], unique=False)
    op.create_foreign_key(None, 'sales_tasks', 'users', ['assigned_to_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales_tasks', type_='foreignkey')
    op.drop_index('idx_tasks_type', table_name='sales_tasks')
    op.drop_index('idx_tasks_assigned_user', table_name='sales_tasks')
    op.alter_column('sales_tasks', 'salesperson_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('sales_tasks', 'parent_lead_conversion')
    op.drop_column('sales_tasks', 'auto_created')
    op.drop_column('sales_tasks', 'assigned_to_user_id')
    op.drop_column('sales_tasks', 'task_type')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_column('leads', 'conversion_completed_by_id')
    op.drop_column('leads', 'conversion_completed_at')
    op.drop_column('leads', 'conversion_checklist_complete')
    op.drop_column('leads', 'handoff_completed_date')
    op.drop_column('leads', 'handoff_completed')
    op.drop_column('leads', 'handoff_manager_id')
    op.drop_column('leads', 'handoff_date')
    op.drop_column('leads', 'handoff_to_manager')
    op.drop_column('leads', 'student_chat_added_date')
    op.drop_column('leads', 'student_chat_platform')
    op.drop_column('leads', 'student_chat_link')
    op.drop_column('leads', 'student_chat_added')
    op.drop_column('leads', 'shipping_notes')
    op.drop_column('leads', 'shipping_phone')
    op.drop_column('leads', 'shipping_postal_code')
    op.drop_column('leads', 'shipping_city')
    op.drop_column('leads', 'shipping_full_address')
    op.drop_column('leads', 'shipping_details_complete')
    op.drop_column('leads', 'kinyan_notes')
    op.drop_column('leads', 'kinyan_file_url')
    op.drop_column('leads', 'kinyan_method')
    op.drop_column('leads', 'kinyan_signed_date')
    op.drop_column('leads', 'kinyan_signed')
    op.drop_column('leads', 'payment_verified')
    op.drop_column('leads', 'payment_reference')
    op.drop_column('leads', 'payment_completed_method')
    op.drop_column('leads', 'payment_completed_date')
    op.drop_column('leads', 'payment_completed_amount')
    op.drop_column('leads', 'payment_completed')
    # ### end Alembic commands ###
