"""Add requested_course to leads

Revision ID: df86256cca0b
Revises: f2f579992ade
Create Date: 2026-02-12 01:05:12.621605
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'df86256cca0b'
down_revision: Union[str, None] = 'f2f579992ade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('requested_course', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'requested_course')
    # ### end Alembic commands ###
