"""add email templates and attachments support

Revision ID: e3a9ae9a693e
Revises: b421f49e3414
Create Date: 2026-02-11 01:57:26.198852
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'e3a9ae9a693e'
down_revision: Union[str, None] = 'b421f49e3414'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_messages', sa.Column('template_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lead_messages', 'email_templates', ['template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lead_messages', type_='foreignkey')
    op.drop_column('lead_messages', 'template_id')
    # ### end Alembic commands ###
