"""add topics system - topics, lessons, student_lesson_progress tables and course/student fields

Revision ID: f2f579992ade
Revises: 092adbaa71df
Create Date: 2026-02-11 23:57:45.385876
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'f2f579992ade'
down_revision: Union[str, None] = '092adbaa71df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('topics_loop_enabled', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('courses', sa.Column('topics_order', sa.Text(), nullable=True))
    op.add_column('students', sa.Column('entry_point_lesson_id', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('entry_date', sa.Date(), nullable=True))
    op.add_column('students', sa.Column('graduation_date', sa.Date(), nullable=True))
    op.add_column('students', sa.Column('is_graduate', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'is_graduate')
    op.drop_column('students', 'graduation_date')
    op.drop_column('students', 'entry_date')
    op.drop_column('students', 'entry_point_lesson_id')
    op.drop_column('courses', 'topics_order')
    op.drop_column('courses', 'topics_loop_enabled')
    # ### end Alembic commands ###
