"""add_popup_announcements

Revision ID: fabf98f7e965
Revises: 6fa1e9fa08c6
Create Date: 2026-02-19 16:10:31.703604
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'fabf98f7e965'
down_revision: Union[str, None] = '6fa1e9fa08c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
